config/routes.rb
Rails.application.routes.draw do
  resources :idds
  # Thinking will not need this for now since all IDDs will be associated to a project.
  resources :projects do
    resources :idds do
      member do
        patch :complete
      end
    end
  end

  root "projects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idd.rb
class Idd < ApplicationRecord
  belongs_to :project
  def completed?
    !out_of_scope_datetime.blank?
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :idds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/idds_controller.rb
class IddsController < ApplicationController
  before_action :set_idd, only: [:show, :edit, :update, :destroy, :complete]

  before_action :set_project, only: [:new]

  # GET /idds
  # GET /idds.json
  def index
    @idds = Idd.all
  end

  # GET /idds/1
  # GET /idds/1.json
  def show
  end

  # GET /idds/new
  def new
    @idd = Idd.new
  end

  # GET /idds/1/edit
  def edit
  end

  # POST /idds
  # POST /idds.json
  def create
    @idd = Idd.new(idd_params)
#    @idd = @project.idds.create(idd_params)

#redirect_to @project.  Consider this once create is working.

    respond_to do |format|
      if @idd.save
        format.html { redirect_to @idd, notice: 'Idd was successfully created.' }
        format.json { render :show, status: :created, location: @idd }
      else
        format.html { render :new }
        format.json { render json: @idd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idds/1
  # PATCH/PUT /idds/1.json
  def update
    respond_to do |format|
      if @idd.update(idd_params)
        format.html { redirect_to @idd, notice: 'Idd was successfully updated.' }
        format.json { render :show, status: :ok, location: @idd }
      else
        format.html { render :edit }
        format.json { render json: @idd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idds/1
  # DELETE /idds/1.json
  def destroy
    @idd.destroy
    respond_to do |format|
      format.html { redirect_to idds_url, notice: 'Idd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    @idd.update_attribute(:out_of_scope_datetime, Time.now )
    redirect_to project_path, notice: "Marked as out of scope"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idd
      @idd = Idd.find(params[:id])
    end

#### An IDD can be created from a project and as a stand alone.  For standalone a project ID has to be provided during IDD creation.
    def set_project
      if params[:project_id].present?
        @project = Project.find(params[:project_id])
      end
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def idd_params
      params.require(:idd).permit(:integration_id, :integration_name, :integration_type, :originating_system, :destination_system, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:Professional_Services_Org, :Customer_Name, :Sow_Name, :Sow_Hours, :Start_Date, :Go_Live, :Project_Description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idds_helper.rb
module IddsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/idds/_form.html.erb
 <!--


form_for([@project, @project.idds.build]) do |f|

-->
 <%= form_for(idd) do |f|  %>
  <% if idd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idd.errors.count, "error") %> prohibited this idd from being saved:</h2>

      <ul>
      <% idd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :integration_id %>
    <%= f.text_field :integration_id %>
  </div>

  <div class="field">
    <%= f.label :integration_name %>
    <%= f.text_field :integration_name %>
  </div>

  <div class="field">
    <%= f.label :integration_type %>
    <%= f.text_field :integration_type %>
  </div>

  <div class="field">
    <%= f.label :originating_system %>
    <%= f.text_field :originating_system %>
  </div>

  <div class="field">
    <%= f.label :destination_system %>
    <%= f.text_field :destination_system %>
  </div>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/idds/_idd.html.erb
<!-- <%= link_to idd.integration_id, idd_path(idd) %> |

<%= link_to "Mark Out of Scope", complete_project_idd_path(@project, idd.id), method: :patch %>
<%= link_to "Delete IDD", project_idd_path(@project, idd), method: :delete, data: { confirm: "Are you sure?"} %>
<br> -->
<tr>
  <td>
    <div class="idd">
      <%= link_to idd.integration_id, idd_path(idd) %>
    </div>
  </td>
  <td>
    <%= idd.integration_name %></td><td>
    <%= idd.integration_type %></td><td>
    <%= idd.originating_system %></td><td>
    <%= idd.destination_system %>

  </td>
  <td>
    <% if !idd.completed? %>
    <div class="complete">
      <%= link_to "Mark Out of Scope", complete_project_idd_path(@project, idd.id), method: :patch %>
    </div>
    <% end %>
    <div class="trash">
      <%= link_to "Edit", edit_project_idd_path(@project, idd) %>
    </div>
    <div class="trash">
      <%= link_to "Delete", project_idd_path(@project, idd), method: :delete, data: { confirm: "Are you sure?"} %>
    </div>


  </td>
</tr>

app/views/idds/edit.html.erb
<h1>Editing Idd</h1>

<%= render 'form', idd: @idd %>

<%= link_to 'Show', @idd %> |
<%= link_to 'Back', idds_path %>

app/views/idds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Idds</h1>

<table>
  <thead>
    <tr>
      <th>Integration</th>
      <th>Integration name</th>
      <th>Integration type</th>
      <th>Originating system</th>
      <th>Destination system</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idds.each do |idd| %>
      <tr>
        <td><%= idd.integration_id %></td>
        <td><%= idd.integration_name %></td>
        <td><%= idd.integration_type %></td>
        <td><%= idd.originating_system %></td>
        <td><%= idd.destination_system %></td>
        <td><%= idd.project.Sow_Name %></td>
        <td><%= link_to 'Show', idd %></td>
        <td><%= link_to 'Edit', edit_idd_path(idd) %></td>
        <td><%= link_to 'Destroy', idd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/idds/new.html.erb
<h1>New Idd</h1>

<%= render 'form', idd: @idd %>

<%= link_to 'Back', idds_path %>

app/views/idds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Integration:</strong>
  <%= @idd.integration_id %>
</p>

<p>
  <strong>Integration name:</strong>
  <%= @idd.integration_name %>
</p>

<p>
  <strong>Integration type:</strong>
  <%= @idd.integration_type %>
</p>

<p>
  <strong>Originating system:</strong>
  <%= @idd.originating_system %>
</p>

<p>
  <strong>Destination system:</strong>
  <%= @idd.destination_system %>
</p>

<p>
  <strong>Project:</strong>
  <%= link_to @idd.project.Sow_Name, project_path(@idd.project.id) %>
</p>

<%= link_to 'Edit', edit_idd_path(@idd) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IddshareApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">iddshare</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Projects', projects_path %></li>
            <li><%= link_to 'IDDs', idds_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Create <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'New Project', new_project_path %></li>
                <li><%= link_to 'New IDD', new_idd_path %></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
          </ul>
        </div>
      </div>
    </nav>
<div class="container-fluid">

    <%= yield %>
</div>





  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Professional_Services_Org %>
    <%= f.text_field :Professional_Services_Org %>
  </div>

  <div class="field">
    <%= f.label :Customer_Name %>
    <%= f.text_field :Customer_Name %>
  </div>

  <div class="field">
    <%= f.label :Sow_Name %>
    <%= f.text_field :Sow_Name %>
  </div>

  <div class="field">
    <%= f.label :Sow_Hours %>
    <%= f.number_field :Sow_Hours %>
  </div>

  <div class="field">
    <%= f.label :Start_Date %>
    <%= f.date_select :Start_Date %>
  </div>

  <div class="field">
    <%= f.label :Go_Live %>
    <%= f.date_select :Go_Live %>
  </div>

  <div class="field">
    <%= f.label :Project_Description %>
    <%= f.text_area :Project_Description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-15 col-md-offset-.5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Projects</h4>
      </div>
      <div class="panel-body">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>PSO</th>
              <th>Customer</th>
              <th>SOW Name</th>
              <th>SOW Hours</th>
              <th>Start Date</th>
              <th>Go-Live Date</th>
              <th>Project Description</th>
              <th colspan="5"></th>
            </tr>
          </thead>

          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td><%= project.Professional_Services_Org %></td>
                <td><%= project.Customer_Name %></td>
                <td><%= project.Sow_Name %></td>
                <td><%= project.Sow_Hours %></td>
                <td><%= project.Start_Date %></td>
                <td><%= project.Go_Live %></td>
                <td><%= project.Project_Description %></td>
                <td><%= link_to 'Show', project %></td>
                <td><%= link_to 'Edit', edit_project_path(project) %></td>
                <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-15 col-md-offset-.5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Project</h4>
      </div>
      <div class="panel-body">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>PSO</th>
              <th>Customer</th>
              <th>SOW Name</th>
              <th>SOW Hours</th>
              <th>Start Date</th>
              <th>Go-Live Date</th>
              <th colspan="5"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @project.Professional_Services_Org %></td>
              <td><%= @project.Customer_Name %></td>
              <td><%= @project.Sow_Name %></td>
              <td><%= @project.Sow_Hours %></td>
              <td><%= @project.Start_Date %></td>
              <td><%= @project.Go_Live %></td>

              <td><%= link_to 'Edit', edit_project_path(@project) %> |
                <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          </tbody>
          <p>
            <strong>Project description:</strong>
            <%= @project.Project_Description %>
          </p>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-15 col-md-offset-.5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Project IDDs</h4>
      </div>
      <div class="panel-body">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Integration ID</th>
              <th>Integration Name</th>
              <th>Integration Type</th>
              <th>From Sys</th>
              <th>To Sys</th>
              <th colspan="5">Actions</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <div id="idds_wrapper">
                <%= render @project.idds %>
              </div>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        <%= link_to 'Create New IDD', new_project_idd_path(@project), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>




<!-- <div id="idds_wrapper">
<% @project.idds.each do |idd| %>
<%= link_to idd.integration_id, idd_path(idd) %>
<%= link_to "Delete IDD", project_idd_path(@project, idd), method: :delete, data: { confirm: "Are you sure?"} %>
<br>
<% end %>
</div> -->